In [43]:
import random
import array
import numpy as np


In [3]:
vector_row = np.array([1, 2, 3])
print(vector_row)

[1 2 3]


In [76]:

def genData(N, d):
    result = []
    for i in range(N):
        vector = []
        for k in range(d):
            x = random.randint(1,100)
            vector.append(random.randint(1,100))
        result.append(vector)
    result1 = np.array(result)
    print(result1)
    return result1
    

sample = genData(4,3)


[[ 40  45 100]
 [ 32  91   1]
 [ 20  99  14]
 [ 87  48  64]]
[32 91  1]


In [91]:
def avgSample(sample, w):
    sum = 0
    for v in range(len(sample)):
        sum += w[v] * sample[v]
    return sum/len(sample)

weight = np.array([1,2,3,4])
avgSample(sample, weight)

array([128., 179., 100.])

In [90]:
print(2*sample)
print(len(sample))

[[ 80  90 200]
 [ 64 182   2]
 [ 40 198  28]
 [174  96 128]]
4
